# Install Maven during the build
[build.install]
  command = "apt-get update && apt-get install -y maven"

# Build settings
[build]
  base = ""
  publish = "/target/classes"
  command = """
    export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    export PATH=$PATH:/usr/bin/maven/bin
    mvn clean
    mvn install
    mvn package
    mvn compile
    mvn exec:java
  """

[build.environment]
  JAVA_HOME = "/usr/lib/jvm/java-11-openjdk-amd64"

# Use a custom Docker image with Maven pre-installed
[build.processing]
  docker = true
  image = "openjdk:11-jdk"
  entrypoint = "/bin/bash"
  command = """
    apt-get update &&
    apt-get install -y maven &&
    rm -rf /var/lib/apt/lists/* &&
    mvn clean install
  """
