[[build]]
  command = "export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64 && wget https://dlcdn.apache.org/maven/maven-3/3.9.7/binaries/apache-maven-3.9.7-bin.tar.gz && tar -xvf apache-maven-3.9.7-bin.tar.gz"
  publish = "target"
