[build.install]
  command = "apt-get update && apt-get install -y maven"

[build]
  base = ""
  publish = "/target/classes"
  command = """
    export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    export PATH=$PATH:/opt/maven/bin
    mvn clean
    mvn install
    mvn package
    mvn compile
    mvn exec:java
  """

[build.environment]
  JAVA_HOME = "/usr/lib/jvm/java-11-openjdk-amd64"
